name: Build & Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false	# let the other image finish even if one fails
      matrix:
        include:
          - variant: normal
            dockerfile: ./image/Dockerfile
            tag-suffix: ""
          - variant: pyinstaller
            dockerfile: ./image/Dockerfile.pynstaller
            tag-suffix: "pynstaller"
          - variant: nuitka
            dockerfile: ./image/Dockerfile.nuitka
            tag-suffix: nuitka
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if the image already exists
        id: check
        run: |
          SUFFIX=${{ matrix.tag-suffix }}
          TAG=$(cat image/tag)
          [ -n "$SUFFIX" ] && TAG="${TAG}-${SUFFIX}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          if docker manifest inspect milansimanek/cert-manager:$TAG > /dev/null 2>&1
          then
            echo "image[$TAG] already exists, nothing to do."
            echo "build=false" >> $GITHUB_OUTPUT
          else
            echo "Image[$TAG] is not present in Docker HUB -> building..."
            echo "build=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        if: steps.check.outputs.build == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.check.outputs.build == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: steps.check.outputs.build == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        if: steps.check.outputs.build == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: milansimanek/cert-manager
          tags: |
            type=raw,value=${{ steps.check.outputs.tag }}
#            type=raw,value=latest

      - name: Build and push - ${{ matrix.variant }}
        if: steps.check.outputs.build == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/arm/v7,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.variant }}
          cache-to: type=gha,scope=${{ matrix.variant }},mode=max
          